tool_name: "Neural Network Optimizer"
tool_description: "Advanced tool for optimizing neural networks, enhancing performance and accuracy."

env_vars:
  NN_API_KEY:
    description: "API key for accessing the Neural Network Optimization service"
    default: ""
  OPTIMIZER_TYPE:
    description: "Type of optimizer (e.g., 'adam', 'sgd', 'rmsprop')"
    default: "adam"
  LEARNING_RATE:
    description: "Learning rate (float between 0.0001 and 0.1)"
    default: 0.001
