tool_name: "Quantum Data Synthesizer modified"
tool_description: "Advanced tool for synthesizing and analyzing quantum data sets, processing complex quantum information and generating visualizations."

env_vars:
  QUANTUM_API_TOKEN:
    description: "Token for accessing the Quantum Computing API"
    default: ""
  ENTANGLEMENT_THRESHOLD:
    description: "Threshold for quantum entanglement detection (float between 0 and 1)"
    default: 0.5
  MAX_QUBITS:
    description: "Maximum number of qubits to process simultaneously"
    default: 32
